#!/bin/bash

# Color Palette
export WHITE=0xffffffff
export BLACK=0xff181926
export GREY=0xff939ab7
export GREEN=0xffa6da95
export TRANSPARENT=0x00000000

# -- Smoking Anime Girl BG Scheme
export PRIMARY=0xff342B4C
export SECONDARY=0xff64597D
export TERTIARY=0xffFFF8FF

export BAR_COLOR=$PRIMARY
export ITEM_BG_COLOR=$SECONDARY
export ACCENT_COLOR=$TERTIARY
export BORDER_COLOR=$SECONDARY
export ICON_COLOR=$WHITE
export LABEL_COLOR=$WHITE
export POPUP_BACKGROUND_COLOR=$PRIMARY
export POPUP_BORDER_COLOR=$SECONDARY
export SHADOW_COLOR=$BLACK
export BACKGROUND_1=0x603c3e4f
export BACKGROUND_2=0x60494d64
