#!/bin/bash

##### Color Palette #####
source "$CONFIG_DIR/colors.sh"

PLUGIN_DIR="$CONFIG_DIR/plugins"
ITEM_DIR="$CONFIG_DIR/items"

##### Bar Appearance #####
bar=(
  height=32
  blur_radius=30
  position=top
  sticky=off
  padding_left=5
  padding_right=5
  color=$BAR_COLOR
  corner_radius=8
  margin=8
  y_offset=2
  shadow=true
  border_color=$BORDER_COLOR
  border_width=1
)
sketchybar --bar "${bar[@]}"   

##### Changing Defaults #####
defaults=(
  updates=when_shown
  icon.font="SF Pro:Semibold:15.0"
  icon.color=$WHITE
  label.font="SF Pro:Semibold:15.0"
  label.color=$WHITE
  background.color=$ITEM_BG_COLOR
  background.corner_radius=5
  background.height=24
  padding_left=5
  padding_right=5
  label.padding_left=4
  label.padding_right=10
  icon.padding_left=10
  icon.padding_right=4
  popup.background.border_width=2
  popup.background.corner_radius=8
  popup.background.border_color=$POPUP_BORDER_COLOR
  popup.background.color=$POPUP_BACKGROUND_COLOR
  popup.blur_radius=20
  popup.background.shadow.drawing=on
)
sketchybar --default "${defaults[@]}"

##### Left Side Items #####
source $ITEM_DIR/spaces.sh
source $ITEM_DIR/front_app.sh

##### Right Side of Notch #####
# source $ITEM_DIR/media.sh
source $ITEM_DIR/spotify.sh

##### Right Side Items #####
source $ITEM_DIR/calendar.sh
source $ITEM_DIR/volume.sh
source $ITEM_DIR/battery.sh
source $ITEM_DIR/cpu.sh

##### Finalizing Setup #####
sketchybar --update
echo "sketchybar config loaded..."

# Start
# brew services start sketchybar

# Stop
# brew services stop sketchybar

# Restart
# brew services restart sketchybar
