#!/bin/bash

options=(
	style=round
	width=2.0
	hidpi=off
	active_color=0xff64597D
	# inactive_color=0xff414550 # standard
  inactive_color=00000000 # workaround for ventura issue
)

borders "${options[@]}"
